[data_location]
#;fits_folder = D:\AstroData\CEERS_simulations_p3_for_visualization_tutorial
#;fits_jwst = D:\AstroData\JWST_initial_spectra
#;output_folder = D:\Dropbox\Astrophysics\Data\NIRSPEC_ml
#;
#;fits_folder = /mnt/AstroData/Observations/CEERS_spectra_visualization_tutorial
#;output_folder = /home/vital/Dropbox/Astrophysics/Data/NIRSPEC_ml

fits_folder = "D:/AstroData/CEERS_spectra_visualization_tutorial"
output_folder = "D:/Dropbox/Astrophysics/Data/NIRSPEC_ml"


[jwst_spectra]
obj_list = ["obj4590", "obj8140", "obj9922", "obj10612"]
z_array = [7.662,8.498,5.276,2.742]
noise_region_array = [5050,5150]
norm_flux = 1

[NIRSpec_params]
G140M_wave_lims_array=[0.5,2.0]
G140M_R_lims_array=[355.0,1436.0]

G235M_wave_lims_array=[1.5,3.5]
G235M_R_lims_array=[636.0,1500.0]

G395M_wave_lims_array=[2.5,6.0]
G395M_R_lims_array=[631.0,1530.0]

PRISM_wave_lims_array=[0.5,6.0]
PRISM_R_lims_array=[30.0,422.0]


[ml_grid_design]
SN_low_limit = 2.5
box_size_pixels = 11
seed_value = 1234
nirspec_resolution_um = 0.00106
sample_size = 500000
training_size = 400000
sample_line_percentage = 50
mask_max_size = 750
training_params_file = "nirspec_training_params_grid.csv"
mu_limits_array = [3,7]

nirspec_wavelength_limits_um_array = [0.6,5.3]

Deltalambda_boundaries_um_array = [0.00018,0.0036]
v_pixel_kmpers_array = [80,215]

sigma_gas_boundaries_kms_array = [50,500]
sigma_gas_boundaries_um_array = [0.0001,0.01]
sigma_gas_boundaries_A_array = [1,100]

amp_array = [0.1,0.25,0.75,1,2,3,4,5,10,100,1000]
sigma_gas_um_array = [0.0001, 0.0003, 0.0006, 0.001, 0.003, 0.006, 0.01, 0.03, 0.06, 0.01, 0.03]
delta_lambda_um_array = [0.00018,0.0005,0.00075,0.001,0.0014,0.0018,0.0022,0.0026,0.003,0.0033,0.0036]
noise_array = [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 1.5, 2, 2.5, 4]


[ml_grid_design_v2]
amp_array = [0.1,0.25,0.75,1,2,3,4,5,10,100,1000]
sigma_gas_um_array = [0.0001, 0.0003, 0.0006, 0.001, 0.003, 0.006, 0.01, 0.03, 0.06, 0.01, 0.03]
delta_lambda_um_array = [0.00018,0.0005,0.00075,0.001,0.0014,0.0018,0.0022,0.0026,0.003,0.0033,0.0036]
noise_array = [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 1.5, 2, 2.5, 4]


[amp_distribution]
param_label = "amp"
dist = "uniform"
units = "flux"
low_limit = 0.1
high_limit = 1000

[mu_index_distribution]
param_label = "mu_index"
dist = "discrete_uniform"
units = "pix"
low_limit = 0
high_limit = "box_size"

[sigma_distribution]
param_label = "sigma"
dist = "uniform"
units = "um"
low_limit = 0.0001
high_limit = 0.01

[lambda_step_distribution]
param_label = "lambda_step"
dist = "uniform"
units = "um"
low_limit = 0.00018
high_limit = 0.0036

[noise_distribution]
param_label = "noise"
dist = "uniform"
units = "flux"
low_limit = 0.01
high_limit = 2

[amp_noise_ratio_distribution]
param_label = "amp_noise_ratio"
dist = "uniform"
units = "none"
low_limit = 0.05
high_limit = 1000

[sigma_lambda_ratio_distribution]
param_label = "sigma_lambda_ratio"
dist = "uniform"
units = "none"
low_limit = 0.2
high_limit = 2.5

[n_cont10_distribution]
param_label = "n_cont10"
dist = "uniform"
units = "flux"
low_limit = 0
high_limit = 10

[n_cont1_distribution]
param_label = "n_cont1"
dist = "uniform"
units = "s"
low_limit = 0.5
high_limit = 1